//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEvenement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenement()
        {
            this.InscriptionUserEvenement = new HashSet<InscriptionUserEvenement>();
        }
    
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<int> Duree { get; set; }
        public Nullable<System.DateTime> DateLimiteInscription { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<int> IdTrancheAge { get; set; }
        public Nullable<int> IdAdresse { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual TrancheAge TrancheAge { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscriptionUserEvenement> InscriptionUserEvenement { get; set; }
    }
}
