//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEvenement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paiement()
        {
            this.PaiementUserResa = new HashSet<PaiementUserResa>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Montant { get; set; }
        public string Libelle { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
        public Nullable<bool> PaiementAJour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaiementUserResa> PaiementUserResa { get; set; }
    }
}
