//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEvenement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.InscriptionUserEvenement = new HashSet<InscriptionUserEvenement>();
            this.PaiementUserResa = new HashSet<PaiementUserResa>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<bool> Genre { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DateAdhesion { get; set; }

        public Nullable<int> IdTrancheAge { get; set; }
        public Nullable<int> IdRole { get; set; }
        public Nullable<int> IdAdresse { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscriptionUserEvenement> InscriptionUserEvenement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaiementUserResa> PaiementUserResa { get; set; }
        public virtual Role Role { get; set; }
        public virtual TrancheAge TrancheAge { get; set; }

       
    }
}
